version: '2'
services:
  web:
    image: tomcat:9.0
    ports:
      - "8080:8080"
    volumes:
      - ./target/ali.malikeh.war:/usr/local/tomcat/webapps/ROOT.war
      - ./target/ali.malikeh:/usr/local/tomcat/webapps/ROOT