version: '3'
services:
  web:
    image: tomcat:9.0
    ports:
      - "8080:8080"
    volumes:
      - ./target/ali.malikeh.war:/usr/local/tomcat/webapps/ROOT.war
      - ./target/ali.malikeh:/usr/local/tomcat/webapps/ROOT
#    command: bash -c "cd /usr/local/tomcat && mv webapps/ROOT/WEB-INF/lib/sqlite-jdbc-3.27.2.jar lib && bin/catalina.sh run"