version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "33060:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'mypasswd'
#
  react:
    build: ./react-app
    ports:
      - "3000:80"
    links:
      - web
    depends_on:
      - web