version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - db:jobounja
    depends_on:
      - db

  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'